package com.qh.half.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGIN_USER.
 */
public class LoginUser {

    private String userid;
    private String userPhoto;
    private String userName;

    public LoginUser() {
    }

    public LoginUser(String userid, String userPhoto, String userName) {
        this.userid = userid;
        this.userPhoto = userPhoto;
        this.userName = userName;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getUserPhoto() {
        return userPhoto;
    }

    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

}
